sudo: required
services:
  - docker
before_install:
  - docker build -t t2nair/multi-client-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true t2nair/multi-client-test npm run test
after_success:
  - docker build -t t2nair/multi-client ./client
  - docker build -t t2nair/multi-nginx ./nginx
  - docker build -t t2nair/multi-server ./server
  - docker build -t t2nair/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push t2nair/multi-client
  - docker push t2nair/multi-nginx
  - docker push t2nair/multi-server
  - docker push t2nair/multi-worker