version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '3090:5432'
  redis:
    image: 'redis:latest'
  nginx:
    restart: always
    depends_on:
      - client
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'  
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    depends_on:
      - postgres  
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
  client:
    build:
        dockerfile: Dockerfile.dev
        context: ./client
    volumes:
        - /app/node_modules
        - ./client:/app
  worker:
      build:
          dockerfile: Dockerfile.dev
          context: ./worker   
      volumes:
        - /app/node_modules
        - ./worker:/app    
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379  
    

    